# Generated by Django 6.0.5 on 2026-05-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
