# Generated by Django 6.0.5 on 2026-05-19 22:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOrderingSystem', '0002_category_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(blank=True, help_text='kcal counter', null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='dietary_tags',
            field=models.CharField(default='Fresh, Organic', help_text='Comma separated tags', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='preparation_time',
            field=models.IntegerField(default=20, help_text='Time in minutes'),
        ),
        migrations.AddField(
            model_name='food',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='foodOrderingSystem.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodOrderingSystem.user')),
            ],
        ),
    ]
