# Generated by Django 6.0.5 on 2026-05-21 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOrderingSystem', '0004_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(help_text='Full name of the individual receiving the package.', max_length=150)),
                ('contact_person_phone', models.CharField(help_text='Primary phone number for delivery rider coordination.', max_length=20)),
                ('alternative_phone', models.CharField(blank=True, help_text='Secondary number if the primary contact is unreachable.', max_length=20, null=True)),
                ('street_address', models.CharField(help_text='House number, apartment/suite number, block, or street identifier.', max_length=255)),
                ('area_or_neighborhood', models.CharField(help_text='Specific area, block, or neighborhood (e.g., Gulshan, Dhanmondi, Mirpur).', max_length=150)),
                ('city_or_division', models.CharField(help_text='The city or administrative division name (e.g., Dhaka, Chattogram).', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal or ZIP code.', max_length=20, null=True)),
                ('delivery_landmark', models.TextField(blank=True, help_text="Any notable landmarks nearby (e.g., 'Opposite the Jamuna Future Park gate').", null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude tracking coordinate map marker pin.', max_digits=9, max_length=50, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude tracking coordinate map marker pin.', max_digits=9, max_length=50, null=True)),
                ('address_tag', models.CharField(choices=[('HOME', 'Home (All-Day Delivery)'), ('OFFICE', 'Office (Work Hours Delivery)'), ('OTHER', 'Other (Custom/Friends)')], default='HOME', help_text='Categorization label for rapid user selection dashboards.', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Designates if this profile is preferred for instant checkout calculations.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The customer who owns this address record.', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='foodOrderingSystem.user')),
            ],
            options={
                'verbose_name': 'Delivery Address',
                'verbose_name_plural': 'Delivery Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
