# Generated by Django 6.0.5 on 2026-05-21 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOrderingSystem', '0007_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='foodOrderingSystem.orders'),
        ),
    ]
