# Generated by Django 6.0.5 on 2026-06-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOrderingSystem', '0008_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('New', 'New Order'), ('Confirmed', 'Confirm Order'), ('Preparing', 'Food Being Prepared'), ('Pickup', 'Food Pickup'), ('Delivered', 'Food Delivered'), ('Cancelled', 'Cancelled Order')], default='New', max_length=20),
        ),
    ]
